#!/bin/bash

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

IGNORE_GOLDEN=false;
VERBOSE=false;
PLOT=false;
N=3

function show_error {
	>&2 echo -e "${RED}${1}${NC}";
}

function error_n_exit {
        show_error "$1";
        exit $2;
}

function pars_args {
        POSITIONAL=();
	while [[ $# -gt 0 ]] && [[ "$(echo $1 | cut -c-1)" == "-" ]]; 
        do
                key="$1";
                case $key in
			-N)
				N=$2;
				shift # past argument
				shift # past value
				;;
                        -i|--ignore-golden)
                                IGNORE_GOLDEN=true;
                                shift # past argument
                                ;;
			-a|--arguments)
				ARGUMENTS="$ARGUMENTS $2";
				shift # past argument
				shift # past value
				;;
			-v|--verbose)
				VERBOSE=true;
				shift # past argument
				;;
			-p|--plot)
				PLOT=true;
				shift # past argument
				;;
                        --help)
                                >&2 usage;
                                exit 1;
                                ;;
                        *)    # unknown option
				show_error "Unknown option: $1";
                                error_n_exit $(usage) 2;
                                ;;
                esac;
        done
	ORIGINAL=$1;
	shift;
	OPTIMIZED=$@;
}

function usage {
	echo "Usage:	evaluate [OPTIONS]... original updated...";
	echo "\t\t-i|--ignore-golden\tUse to avoid abort when output doesn't match."
        echo "\t\t-a|--arguments=ARGUMENT\tAppend ARGUMENT to the argument list."
}

pars_args $@;

# Creating working directory
while : ; 
do
	name=$(date '+%F %T' | sha256sum | cut -c-10);
	dir=evaldir-$name;
	echo -e "=> Creating working dir $dir";
	mkdir $dir && break;
	echo -e "${RED}==>Failed to create dir $dir";
done

# Creating golden outpu
echo -e "=> Generating golden output."
$ORIGINAL $ARGUMENTS > $dir/golden.out;

# Runing time tests
START=1
$VERBOSE || echo -e "=> Running $N time tests on original binary."
for i in `seq $START $N`;
do
	$VERBOSE && echo -e "=> Running time test on original binary. (Test $i)";
	/usr/bin/time -f "%e %P" -a -o $dir/time_original $ORIGINAL $ARGUMENTS > /dev/null;
done

nu=1;
for program in $OPTIMIZED;
do
	echo -e "=> Generating output of optimized binary $nu ($program).";
	$program $ARGUMENTS > $dir/optimized_$nu.out;
	echo -e "=> Checking output of optimized binary $nu ($program).";
	if [[ "$(cat $dir/golden.out | sha256sum )" == "$(cat $dir/optimized_$nu.out | sha256sum )" ]];
	then
		echo -e "${GREEN}==> Output match.${NC}";
	else	
		if $IGNORE_GOLDEN;
		then
			echo -e "${YELLOW}==> Waring: Output of optimized code number $nu does not match golden output.${NC}"
		else
			echo -e "${RED}==> Error: Output of optimized code number $nu does not match golden output.${NC}"
			error_n_exit "Aborting due to output missmatch" 3;
		fi

	fi

	$VERBOSE || echo -e "=> Running $N time tests on original binary.";
	for i in `seq $START $N`;
	do
		$VERBOSE && echo -e "=> Running time test on optimized binary $nu. (Test $i)";
		/usr/bin/time -f "%e %P" -a -o $dir/time_update_$nu $program $ARGUMENTS > /dev/null;
	done
	nu=$((nu + 1));
done

function calculate_values {
	FIRST=true;
	while read line;
	do 
		CUR_E=$(echo $line | awk '{print $1}')
		CUR_P=$(echo $line | awk '{gsub("[^[:digit:]]+"," "); print $2}')
		if $FIRST; 
		then
			AVG_E[$2]=$CUR_E;
			MAX_E[$2]=$CUR_E;	
			MIN_E[$2]=$CUR_E;

			AVG_P[$2]=$CUR_P
			MAX_P[$2]=$CUR_P
			MIN_P[$2]=$CUR_P
			FIRST=false;
		else
			if (( $(echo "${MAX_E[${2}]} < ${CUR_E}" |bc -l) )); then MAX_E[$2]=$CUR_E; fi	
			if (( $(echo "${MIN_E[${2}]} > ${CUR_E}" |bc -l) )); then MIN_E[$2]=$CUR_E; fi	
			AVG_E[$2]=$(echo "${CUR_E} + ${AVG_E[${2}]}" |bc -l);

			if (( $(echo "${MAX_P[${2}]} < ${CUR_P}" |bc -l) )); then MAX_P[$2]=$CUR_P; fi	
			if (( $(echo "${MIN_P[${2}]} > ${CUR_P}" |bc -l) )); then MIN_P[$2]=$CUR_P; fi	
			AVG_P[$2]=$(echo "${CUR_P} + ${AVG_P[${2}]}" |bc -l);
		fi
	done < $1;
	
	AVG_E[$2]=$(echo "${AVG_E[${2}]} / ${N}" | bc -l | awk '{printf("%.4f\n", $1)}');
	AVG_P[$2]=$(echo "${AVG_P[${2}]} / ${N}" | bc -l | awk '{printf("%.4f\n", $1)}');
}

calculate_values $dir/time_original 0;
echo "Program MaxE MinE AvgE SpeedUp MaxP MinP AvgP" | column -t;
echo "Original ${MAX_E[0]} ${MIN_E[0]} ${AVG_E[0]} ${MAX_P[0]} ${MIN_P[0]} ${AVG_P[0]}" | column -t;
$PLOT && echo "Original		${AVG_E[0]}" >> $dir/plotfile
nu=1
for programs in $OPTIMIZED;
do
	calculate_values $dir/time_update_$nu $nu;
	echo "$programs ${MAX_E[${nu}]} ${MIN_E[${nu}]} ${AVG_E[${nu}]} $(echo "${AVG_E[0]} / ${AVG_E[${nu}]}" |bc -l | awk '{printf("%.4f\n", $1)}') ${MAX_P[${nu}]} ${MIN_P[${nu}]} ${AVG_P[${nu}]}" | column -t;
	$PLOT && echo "${programs}	${AVG_E[${nu}]}" >> $dir/plotfile
	nu=$((nu + 1));
done

$PLOT && echo "set boxwidth 0.75
set style fill solid
set auto y
set title \"Average time comparaison\"
plot \"$dir/plotfile\" using 2:xtic(1) with boxes
set yr [0:GPVAL_DATA_Y_MAX]
pause -1 \"=>Hit return to continue\""> $dir/plotscript
$PLOT && gnuplot $dir/plotscript

