#!/bin/bash

export PARAEVALUAR_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd -P )"

source ${PARAEVALUAR_HOME}/paraevaluar.utils "base"

function help {
cat >&2 <<EOF
Usage:	paraevaluar COMMAND
		COMMAND
			help
			init
			script
			addfile
			eval
			report
EOF
}

function init {
	${PARAEVALUAR_HOME}/paraevaluar.init $@
}

function script {
	${PARAEVALUAR_HOME}/paraevaluar.script $@
}

function evaluate { 
	${PARAEVALUAR_HOME}/paraevaluar.eval $@
}

function report { 
	${PARAEVALUAR_HOME}/paraevaluar.report $@
}

function add {
	${PARAEVALUAR_HOME}/paraevaluar.addfile $@
}

function parse_command {
	case $1 in
		help)
			COMMAND="help"
			;;
	       	init)
			COMMAND="init"
			;;
		script)
			COMMAND="script"
			;;
		add)
			COMMAND="add"
			;;
		eval)
			COMMAND="evaluate"		
			;;
		report)
			COMMAND="report"		
			;;
		*)
			>&2 echo "Unknown command: $1";
			;;
	esac
}

if [[ $# -lt 1 ]]; then 
	>&2 echo "paraevaluar needs at least one argument. \nFor more information run: paraevaluar help";
fi

parse_command $@;
shift;
#parse_args $@;

eval ${COMMAND} $@
