#!/bin/bash

source ${PARAEVALUAR_HOME}/paraevaluar.utils "init"

if [[ -d ${PROJECT_NAME} ]];
then
	if ! assert_user --default-no --text "WARNING: Project already exists. Do you want to override it? [y/N]  ";
	then
		echo "Aborting...";
		exit 0;	
	fi
fi

echo "Creating new paraevaluar project: ${PROJECT_NAME}";

\rm -rf   ${PROJECT_NAME} 
\mkdir -p ${PROJECT_NAME}
\mkdir -p ${PROJECT_NAME}/job-scripts
\mkdir -p ${PROJECT_NAME}/files

\cat > ${PROJECT_NAME}/.vimrc << EOF

EOF
