#!/bin/bash

#SBATCH -J Example
#SBATCH -t 1:00:00

# Enviroment
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/bin/lib
PATH=$PATH:.

# Modules
module load gcc/8.2.0
module load openmpi/3.1.2


pi.3 ./H2O-64.inp > H2O-64.out


